[colors]
background = '#180e208e'
black = '#180e20'
blue = '#74489C'
cursor = '#c5c2c7'
cyan = '#7953C5'
foreground = '#c5c2c7'
green = '#A24D9F'
magenta = '#9655A7'
red = '#A666D5'
tabs = '#c5c2c7'
tabs-active = '#CD73E4'
white = '#c5c2c7'
yellow = '#c5c2c7'
dim-black = '#180e208e'
dim-blue = '#74489C8e'
dim-cyan = '#7953C58e'
dim-foreground = '#c5c2c78e'
dim-green = '#A24D9F8e'
dim-magenta = '#9655A78e'
dim-red = '#A666D58e'
dim-white = '#CD73E48e'
dim-yellow = '#c5c2c78e'
light-black = '#74489C'
light-blue = '#7953C5'
light-cyan = '#A24D9F'
light-foreground = '#9655A7'
light-green = '#A666D5'
light-magenta = '#CD73E4'
light-red = '#c5c2c7'
light-white = '#74489C'
light-yellow = '#7953C5'
