[colors.primary]
background = "#180e20"
foreground = "#c5c2c7"

[colors.cursor]
text = "#180e20"
cursor = "#c5c2c7"

[colors.vi_mode_cursor]
text = "#180e20"
cursor = "#c5c2c7"

[colors.search.matches]
foreground = "#180e20"
background = "#c5c2c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#675d72"
background = "#c5c2c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#180e20"
red = "#74489C"
green = "#7953C5"
yellow = "#A24D9F"
blue = "#9655A7"
magenta = "#A666D5"
cyan = "#CD73E4"
white = "#c5c2c7"

[colors.bright]
black = "#675d72"
red = "#74489C"
green = "#7953C5"
yellow = "#A24D9F"
blue = "#9655A7"
magenta = "#A666D5"
cyan = "#CD73E4"
white = "#c5c2c7"

[colors.dim]
black = "#c5c2c7"
red = "#74489C"
green = "#A666D5"
yellow = "#A24D9F"
blue = "#9655A7"
magenta = "#7953C5"
cyan = "#CD73E4"
white = "#675d72"

